export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headLine: 'Unlimited Transactions',
  description: 'this is the description text',
  buttonLable: 'button',
  imgStart: false,
  img: require('../../images/img3.JPG').default,
  alt: 'car',
  dark: true,
  primary: true,
  darkText: false,
}
export const homeObjTwo = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headLine: 'Unlimited Transactions',
  description: 'this is the description text',
  buttonLable: 'button',
  imgStart: false,
  img: require('../../images/img3.JPG').default,
  alt: 'car',
  dark: true,
  primary: true,
  darkText: false,
}
export const homeObjThree = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headLine: 'Unlimited Transactions',
  description: 'this is the description text',
  buttonLable: 'button',
  imgStart: false,
  img: require('../../images/img3.JPG').default,
  alt: 'car',
  dark: true,
  primary: true,
  darkText: false,
}